site_name: 'SurgeScript Documentation'
theme:
    name: 'material'
pages:
    - 'Introduction': 'index.md'
    - 'Download': 'download.md'
    - 'Crash Course':
        - 'Hello, World!': 'tutorials/hello.md'
        - 'Testing your scripts': 'tutorials/testing.md'
        - 'Introduction to objects': 'tutorials/objects.md'
        - 'Variables': 'tutorials/variables.md'
        - 'Expressions': 'tutorials/expressions.md'
        - 'Conditionals': 'tutorials/conditionals.md'
        - 'Loops': 'tutorials/loops.md'
        - 'Functions': 'tutorials/functions.md'
        - 'Comments': 'tutorials/comments.md'
        - 'Tags': 'tutorials/tags.md'
        - 'Object tree': 'tutorials/object_tree.md'
        - 'Components': 'tutorials/components.md'
        - 'Properties': 'tutorials/properties.md'
        - 'Plugins': 'tutorials/plugins.md'
        - 'Advanced features': 'tutorials/advanced_features.md'
        - 'Best practices': 'tutorials/best_practices.md'
    - 'SurgeScript Reference':
        - 'Application': 'reference/application.md'
        - 'Arguments': 'reference/arguments.md'
        - 'Array': 'reference/array.md'
        - 'Boolean': 'reference/boolean.md'
        - 'Console': 'reference/console.md'
        - 'Date': 'reference/date.md'
        - 'Dictionary': 'reference/dictionary.md'
        - 'GC': 'reference/gc.md'
        - 'Iterator': 'reference/iterator.md'
        - 'Math': 'reference/math.md'
        - 'Number': 'reference/number.md'
        - 'Object': 'reference/object.md'
        - 'Plugin': 'reference/plugin.md'
        - 'String': 'reference/string.md'
        - 'SurgeScript': 'reference/surgescript.md'
        - 'System': 'reference/system.md'
        - 'TagSystem': 'reference/tags.md'
        - 'Time': 'reference/time.md'
    - 'SurgeEngine Reference':
        - 'Actor': 'engine/actor.md'
        - 'Animation': 'engine/animation.md'
        - 'Audio':
            - 'Music': 'engine/music.md'
            - 'Sound': 'engine/sound.md'
        - 'Camera': 'engine/camera.md'
        - 'Collisions':
            - 'Collider': 'engine/collider.md'
            - 'CollisionBall': 'engine/collisionball.md'
            - 'CollisionBox': 'engine/collisionbox.md'
            - 'Sensor': 'engine/sensor.md'
        - 'Entity': 'engine/entity.md'
        - 'Input':
            - 'Input': 'engine/input.md'
            - 'Mouse': 'engine/mouse.md'
        - 'Level': 'engine/level.md'
        - 'Player': 'engine/player.md'
        - 'Prefs': 'engine/prefs.md'
        - 'SurgeEngine': 'engine/surgeengine.md'
        - 'Transform': 'engine/transform.md'
        - 'UI':
            - 'Text': 'engine/text.md'
        - 'Vector2': 'engine/vector2.md'
        - 'Video':
            - 'Screen': 'engine/screen.md'
        - 'Web': 'engine/web.md'
