site_name: 'SurgeScript Documentation'
theme:
    name: 'material'
pages:
    - 'Introduction': 'index.md'
    - 'Download': 'download.md'
    - 'Crash Course':
        - 'Hello, World!': 'tutorials/hello.md'
        - 'Testing your scripts': 'tutorials/testing.md'
        - 'Introduction to objects': 'tutorials/objects.md'
        - 'Variables': 'tutorials/variables.md'
        - 'Expressions': 'tutorials/expressions.md'
        - 'Conditionals': 'tutorials/conditionals.md'
        - 'Loops': 'tutorials/loops.md'
        - 'Functions': 'tutorials/functions.md'
        - 'Comments': 'tutorials/comments.md'
        - 'Tags': 'tutorials/tags.md'
        - 'Object tree': 'tutorials/object_tree.md'
        - 'Components': 'tutorials/components.md'
        - 'Getters & setters': 'tutorials/getters_and_setters.md'
        - 'Plugin system': 'tutorials/plugins.md'
        - 'Advanced features': 'tutorials/advanced_features.md'
        - 'Best practices': 'tutorials/best_practices.md'
    - 'SurgeScript Reference':
        - 'Application': 'reference/application.md'
        - 'Array': 'reference/array.md'
        - 'Arguments': 'reference/arguments.md'
        - 'Boolean': 'reference/boolean.md'
        - 'Console': 'reference/console.md'
        - 'Date': 'reference/date.md'
        - 'Dictionary': 'reference/dictionary.md'
        - 'GC': 'reference/gc.md'
        - 'Math': 'reference/math.md'
        - 'Number': 'reference/number.md'
        - 'Iterator': 'reference/iterator.md'
        - 'Object': 'reference/object.md'
        - 'Plugin': 'reference/plugin.md'
        - 'TagSystem': 'reference/tags.md'
        - 'Time': 'reference/time.md'
        - 'Transform2D': 'reference/transform2d.md'
        - 'String': 'reference/string.md'
        - 'SurgeScript': 'reference/surgescript.md'
        - 'System': 'reference/system.md'
    - 'SurgeEngine Reference':
        - 'Actor': 'surgeengine/actor.md'
        - 'Camera': 'surgeengine/camera.md'
        - 'Entity': 'surgeengine/entity.md'
        - 'Input': 'surgeengine/input.md'
