site_name: 'SurgeScript Documentation'
theme:
    name: 'material'
pages:
    - 'Introduction': 'index.md'
    - 'Download': 'download.md'
    - 'Crash Course':
        - 'Hello, World!': 'tutorials/hello.md'
        - 'Testing your scripts': 'tutorials/testing.md'
        - 'Introduction to objects': 'tutorials/objects.md'
        - 'Variables': 'tutorials/variables.md'
        - 'Expressions': 'tutorials/expressions.md'
        - 'Conditionals': 'tutorials/conditionals.md'
        - 'Loops': 'tutorials/loops.md'
        - 'Functions': 'tutorials/functions.md'
        - 'Comments': 'tutorials/comments.md'
        - 'Tags': 'tutorials/tags.md'
        - 'Object tree': 'tutorials/object_tree.md'
        - 'Components': 'tutorials/components.md'
        - 'Getters & setters': 'tutorials/getters_and_setters.md'
        - 'Advanced Features': 'tutorials/advanced_features.md'
        - 'Best practices': 'tutorials/best_practices.md'
    - 'SurgeScript Reference':
        - 'Application': 'reference/application.md'
        - 'Arguments': 'reference/arguments.md'
        - 'Math': 'reference/math.md'
        - 'Iterator': 'reference/iterator.md'
        - 'Object': 'reference/object.md'
        - 'Transform2D': 'reference/transform2d.md'
        - 'Session': 'reference/session.md'
        - 'System': 'reference/system.md'
    - 'Engine Reference':
        - 'Application': 'reference/application.md'