site_name: 'SurgeScript Documentation'
theme:
    name: 'material'
pages:
    - 'Introduction': 'index.md'
    - 'SurgeScript Crash Course':
        - 'Hello, World!': 'tutorials/hello.md'
        - 'Testing your scripts': 'tutorials/testing.md'
        - 'Introduction to objects': 'tutorials/objects.md'
        - 'Variables': 'tutorials/variables.md'
        - 'Conditionals': 'tutorials/conditionals.md'
        - 'Loops': 'tutorials/loops.md'
        - 'Functions': 'tutorials/functions.md'
        - 'Tags': 'tutorials/tags.md'
        - 'Object tree': 'tutorials/objects.md'
        - 'Components': 'tutorials/components.md'
        - 'Getters & setters': 'tutorials/getters_and_setters.md'
        - 'Advanced Features': 'tutorials/advanced_features.md'
        - 'Best practices': 'tutorials/objects.md'
    - 'Language Reference':
        - 'Application': 'reference/application.md'